import "./globals.css";

export const metadata = {
  title: "StarTracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" bg-gradient-to-br from-emerald-50 to-emerald-100 ">
        {children}
      </body>
    </html>
  );
}
